UPDATE DEVICES
SET DEVICE_NAME = 'АКРОН-01',
    STARTNUMBER_LARGEARCH = 2000
WHERE (ID_DEVICE = 15);

UPDATE DEVICES
SET DEVICE_NAME = 'АКРОН-02-2',
    STARTNUMBER_LARGEARCH = 4000
WHERE (ID_DEVICE = 16);

INSERT INTO DEVICES (ID_DEVICE, SERIAL_NUM, DEVICE_TYPE, DEVICE_NAME, DESCR, N_BITS, ACTUAL, N_CHANNEL, FREQUENCY, CUSTOMER, CUSTOMER_DESCR, FILEFILTER, FORMAT_X, PROCESSING, WINDOWHEADER, TYPEOFFILE, DLL_NAME, GETINFO_FUNCTION_NAME, GETDATA_FUNCTION_NAME, STARTNUMBER_LARGEARCH)
  VALUES (22, '1', 2, 'АКРОН-02-1', NULL, 10, 'Да', 5, 1000, 'Signur2', NULL, 'Результаты Сигнур', '##0.##', '0', 'СИГНУР', '.DAT', 'Import_Signur_2', 'GETINFO_SIGNUR', 'GETDATA_SIGNUR', 4000);

INSERT INTO DEVICES (ID_DEVICE, SERIAL_NUM, DEVICE_TYPE, DEVICE_NAME, DESCR, N_BITS, ACTUAL, N_CHANNEL, FREQUENCY, CUSTOMER, CUSTOMER_DESCR, FILEFILTER, FORMAT_X, PROCESSING, WINDOWHEADER, TYPEOFFILE, DLL_NAME, GETINFO_FUNCTION_NAME, GETDATA_FUNCTION_NAME, STARTNUMBER_LARGEARCH)
  VALUES (23, '1', 2, 'АКРОН-02-3', NULL, 10, 'Да', 5, 1000, NULL, NULL, 'Результаты испытаний РПН(*.lcr)|*.lcr|Все файлы (*.*)|*.*', '##0.##', '0', 'СИГНУР', '.DAT', 'Import_Signur_2', 'GETINFO_SIGNUR', 'GETDATA_SIGNUR', 4000);


SET GENERATOR GEN_DEVICES TO 16;
