program printDOC_p;

uses
  Forms,
  TxFrame in '..\..\..\projects\AppProjects\AppCommon\TxFrame.pas' {TaxxiFrame: TFrame},
  CommonForm_u in '..\..\Dionix\source\CommonForm_u.pas' {CommonForm: TTaxxiForm},
  MenuForm_u in '..\..\Dionix\source\MenuForm_u.pas' {MenuForm: TTaxxiForm},
  MainForm_u in '..\..\Dionix\source\MainForm_u.pas' {MainForm: TTaxxiForm},
  DataModule in '..\..\Dionix\source\DataModule.pas' {DM: TDataModule},
  config_u in '..\..\Dionix\source\config_u.pas',
  ErrorCode_u in '..\..\Dionix\source\ErrorCode_u.pas',
  General_u in '..\..\Dionix\source\General_u.pas',
  utils in '..\..\Dionix\source\utils.pas',
  Street_u in '..\..\Dionix\source\Street_u.pas' {StreetForm: TTaxxiForm},
  SpravForm_u in '..\..\Dionix\source\SpravForm_u.pas' {SpravForm: TTaxxiForm},
  Carpet_u in '..\..\Dionix\source\Carpet_u.pas' {CarpetForm: TTaxxiForm},
  AddNew_u in '..\..\Dionix\source\AddNew_u.pas' {AddNewtForm: TTaxxiForm},
  AddNewCarpet_u in '..\..\Dionix\source\AddNewCarpet_u.pas' {AddNewcarpetForm: TTaxxiForm},
  Client_u in '..\..\Dionix\source\Client_u.pas' {ClientForm: TTaxxiForm},
  UpdateEmployee_u in '..\..\Dionix\source\UpdateEmployee_u.pas' {UpdateEmployeeForm: TTaxxiForm},
  UpdateContract_u in '..\..\Dionix\source\UpdateContract_u.pas' {UpdateContractForm: TTaxxiForm},
  UpdateAppendix_u in '..\..\Dionix\source\UpdateAppendix_u.pas' {UpdateAppendixForm: TTaxxiForm},
  UpdateApp_Dionix_u in '..\..\Dionix\source\UpdateApp_Dionix_u.pas' {UpdateAppForDionixform: TTaxxiForm},
  AddNewAppCarpet_u in '..\..\Dionix\source\AddNewAppCarpet_u.pas' {AddNewAppcarpetForm: TTaxxiForm},
  selectclient_u in '..\..\Dionix\source\selectclient_u.pas' {SelectClientForm: TTaxxiForm},
  Updatecard_u in '..\..\Dionix\source\Updatecard_u.pas' {UpdateCardForm: TTaxxiForm},
  Updateclient_u in '..\..\Dionix\source\Updateclient_u.pas' {UpdateClientForm: TTaxxiForm},
  holidays_u in '..\..\Dionix\source\holidays_u.pas' {HolidaysForm: TTaxxiForm},
  ways_u in '..\..\Dionix\source\ways_u.pas' {WaysForm: TTaxxiForm},
  AddNewWay_u in '..\..\Dionix\source\AddNewWay_u.pas' {AddNewWayForm: TTaxxiForm},
  clientdionix_u in '..\..\Dionix\source\clientdionix_u.pas' {ClientDionixForm: TTaxxiForm},
  updateschedule_u in '..\..\Dionix\source\updateschedule_u.pas' {UpdatescheduleForm: TTaxxiForm},
  District_u in '..\..\Dionix\source\District_u.pas' {DistrictForm: TTaxxiForm},
  AddNewdistrict_u in '..\..\Dionix\source\AddNewdistrict_u.pas' {AddNewDistrictForm: TTaxxiForm},
  addItemTo_u in '..\..\Dionix\source\addItemTo_u.pas' {AddItemToForm: TTaxxiForm},
  addDistrictToWay_u in '..\..\Dionix\source\addDistrictToWay_u.pas' {addDistrictToWayForm: TTaxxiForm},
  waylistPlan_u in '..\..\Dionix\source\waylistPlan_u.pas' {WayListPlanForm: TTaxxiForm},
  waylist_u in '..\..\Dionix\source\waylist_u.pas' {WayListForm: TTaxxiForm},
  Import_u in '..\..\Dionix\source\Import_u.pas' {ImportForm: TTaxxiForm},
  address_u in '..\..\Dionix\source\address_u.pas' {AddressForm: TTaxxiForm},
  selectaddress_u in '..\..\Dionix\source\selectaddress_u.pas' {SelectAddressForm: TTaxxiForm},
  waylistFact_u in '..\..\Dionix\source\waylistFact_u.pas' {WayListfactForm: TTaxxiForm},
  Search_u in '..\..\Dionix\source\Search_u.pas' {SearchForm: TTaxxiForm},
  rxStrUtils in '..\..\Dionix\source\rxStrUtils.pas',
  carpetlist_u in '..\..\Dionix\source\carpetlist_u.pas' {CarpetListForm: TTaxxiForm},
  CarpetsOnDay_U in '..\..\Dionix\source\CarpetsOnDay_U.pas' {CarpetsOnday_Form: TTaxxiForm},
  waylistother_u in '..\..\Dionix\source\waylistother_u.pas' {WayListOtherForm: TTaxxiForm},
  colormap_u in '..\..\Dionix\source\colormap_u.pas' {ColormapForm: TTaxxiForm},
  losedcarpets_u in '..\..\Dionix\source\losedcarpets_u.pas' {LosedcarpetsForm: TTaxxiForm},
  appcarpets_u in '..\..\Dionix\source\appcarpets_u.pas' {appcarpetsForm: TTaxxiForm},
  manager_u in '..\..\Dionix\source\manager_u.pas' {ManagerForm: TTaxxiForm},
  AddNewManager_u in '..\..\Dionix\source\AddNewManager_u.pas' {AddNewmanagerForm: TTaxxiForm},
  warehouse_U in '..\..\Dionix\source\warehouse_U.pas' {wareHouseForm: TTaxxiForm},
  Appcarpetslist_u in '..\..\Dionix\source\Appcarpetslist_u.pas' {AppcarpetsListForm: TTaxxiForm},
  services_u in '..\..\Dionix\source\services_u.pas' {ServicesForm: TTaxxiForm},
  ServiceCashier_u in '..\..\Dionix\source\ServiceCashier_u.pas' {ServicesCashierForm: TTaxxiForm},
  GetClient_u in '..\..\Dionix\source\GetClient_u.pas' {GetClientForm: TTaxxiForm},
  Lowadresses_u in '..\..\Dionix\source\Lowadresses_u.pas' {LowAddressesForm: TTaxxiForm},
  services_for_lowaddress_u in '..\..\Dionix\source\services_for_lowaddress_u.pas' {Services_for_lowaddressForm: TTaxxiForm},
  SelectCashier_u in '..\..\Dionix\source\SelectCashier_u.pas' {SelectCashierForm: TTaxxiForm},
  waysLoad_u in '..\..\Dionix\source\waysLoad_u.pas' {waysLoadForm: TTaxxiForm},
  ServiceCheckCashier_u in '..\..\Dionix\source\ServiceCheckCashier_u.pas' {ServiceCheckCashierForm: TTaxxiForm},
  OKCANCL1 in '..\..\Dionix\source\OKCANCL1.PAS' {OKBottomDlg},
  GetDateInterval in '..\..\Dionix\source\GetDateInterval.pas' {GetDateInterval_form},
  act_U in '..\..\Dionix\source\act_U.pas' {ActsForm: TTaxxiForm},
  driver_u in '..\..\Dionix\source\driver_u.pas' {DriverForm: TTaxxiForm},
  Expeditor_u in '..\..\Dionix\source\Expeditor_u.pas' {ExpeditorForm: TTaxxiForm},
  driver_car_u in '..\..\Dionix\source\driver_car_u.pas' {Driver_CarForm: TTaxxiForm},
  Car_u in '..\..\Dionix\source\Car_u.pas' {CarForm: TTaxxiForm},
  AddNewcar_u in '..\..\Dionix\source\AddNewcar_u.pas' {AddNewCarForm: TTaxxiForm},
  GetDateInterval_u in '..\..\Dionix\source\GetDateInterval_u.pas' {GetDateIntervalForm},
  statistica_u in '..\..\Dionix\source\statistica_u.pas' {StatisticaForm},
  ServiceCheckLowAddres_u in '..\..\Dionix\source\ServiceCheckLowAddres_u.pas' {ServiceCheckLowAddressForm},
  Phone_u in '..\..\Dionix\source\Phone_u.pas' {PhoneForm},
  BillInfo_u in '..\..\Dionix\source\BillInfo_u.pas' {BillInfoForm},
  OKCANCL2 in '..\..\Dionix\source\OKCANCL2.pas' {OKRightDlg},
  GetBill_u in '..\..\Dionix\source\GetBill_u.pas' {GetBillForm},
  Pricelist_u in '..\..\Dionix\source\Pricelist_u.pas' {PricelistForm},
  LowAddressAdm_u in '..\..\Dionix\source\LowAddressAdm_u.pas' {LowAddressAdmForm},
  AppsInfoForBill_u in '..\..\Dionix\source\AppsInfoForBill_u.pas' {AppsInfoForBillForm},
  ClientTypes_u in '..\..\Dionix\source\ClientTypes_u.pas' {ClientTypesForm},
  SelectManager_u in '..\..\Dionix\source\SelectManager_u.pas' {SelectManagerForm},
  PaymentManager_U in '..\..\Dionix\source\PaymentManager_U.pas' {PaymentManagerForm},
  DbGridUnit in '..\..\..\PROJECTS\AppProjects\AppCommon\DbGridUnit.pas' {DbGridFrame: TFrame},
  badvyvoz_U in '..\..\Dionix\source\badvyvoz_U.pas' {BadVyvozForm},
  reasonsForn in '..\..\Dionix\source\reasonsForn.pas' {ReasonsForm},
  pril_U in '..\..\Dionix\source\pril_U.pas' {PrilForm},
  ProvidersForm_u in '..\..\Dionix\source\ProvidersForm_u.pas' {ProvidersForm},
  CreateNewCard_u in '..\..\Dionix\source\CreateNewCard_u.pas' {CreateNewCardForm},
  updateProviderForm_u in '..\..\Dionix\source\updateProviderForm_u.pas' {UpdateProviderForm},
  setProviderForm_u in '..\..\Dionix\source\setProviderForm_u.pas' {SetProviderForm},
  setBS_BF_u in '..\..\Dionix\source\setBS_BF_u.pas' {SetBS_BFForm},
  BS_BF_u in '..\..\Dionix\source\BS_BF_u.pas' {BS_BFForm},
  GetDate_u in '..\..\Dionix\source\GetDate_u.pas' {GetDateForm},
  Propuska_u in '..\..\Dionix\source\Propuska_u.pas' {PropuskaForm},
  sqlmonitor_u in '..\..\Dionix\source\sqlmonitor_u.pas' {SQLMonitorForm},
  ExchRates_1_u in '..\..\Dionix\source\ExchRates_1_u.pas' {ExchRates_1_Form},
  ExchRates_2_u in '..\..\Dionix\source\ExchRates_2_u.pas' {ExchRates_2_Form},
  LA_for_doc_u in '..\..\Dionix\source\LA_for_doc_u.pas' {LA_for_doc_Form},
  GetDate2_u in '..\..\Dionix\source\GetDate2_u.pas' {GetDate2Form},
  work1c_u in '..\..\Dionix\source\work1c_u.pas' {Work1CForm},
  SelectContractForm_u in '..\..\Dionix\source\SelectContractForm_u.pas' {SelectContractForm},
  ACc_deliv_hist_u in '..\..\Dionix\source\ACc_deliv_hist_u.pas' {ACC_DELIV_HIST_Form},
  attaddress_u in '..\..\Dionix\source\attaddress_u.pas' {AttAddressForm},
  WayListFactProvider_u in '..\..\Dionix\source\waylistFactProvider_u.pas' {WayListfactProviderForm},
  WdUnit in '..\..\Dionix\source\WdUnit.pas' {WordModule: TDataModule},
  MInWord in '..\..\Dionix\source\MInWord.pas',
  clearDirtyWeight_u in '..\..\Dionix\source\clearDirtyWeight_u.pas' {ClearDirtyWeightForm},
  AddressGroups_u in '..\..\Dionix\source\AddressGroups_u.pas' {AddressGroupsForm},
  GridReport in '..\..\Dionix\source\Report\GridReport.pas',
  RFIDS_U in '..\..\Dionix\source\RFIDS_U.pas' {RFIDSForm},
  waylistfactquestionable_u in '..\..\Dionix\source\waylistfactquestionable_u.pas' {WayListfactQuestionableForm},
  WaylistOtmena_u in '..\..\Dionix\source\WaylistOtmena_u.pas' {WayListOtmenaForm},
  WaylistNedostavlen_u in '..\..\Dionix\source\WaylistNedostavlen_u.pas' {WayListNedostavlenForm},
  map_geocode_u in '..\..\Dionix\source\map_geocode_u.pas' {MapGeoGode_form},
  constMsg_u in '..\..\Dionix\source\constMsg_u.pas',
  LoginForm_u in '..\..\Dionix\source\LoginForm_u.pas' {LoginForm},
  CRM_ADDEventUnit in '..\..\Dionix\source\CRM_ADDEventUnit.pas' {CRMAddEventForm},
  CRM_ADDEvent_10_Unit in '..\..\Dionix\source\CRM_ADDEvent_10_Unit.pas' {CRMAddEvent_10_Form},
  CRM_ADDEvent_20_Unit in '..\..\Dionix\source\CRM_ADDEvent_20_Unit.pas' {CRMADDEvent_20_Form},
  crm_add_event_30_unit in '..\..\Dionix\source\crm_add_event_30_unit.pas' {CRMADDEvent_30_Form},
  crm_add_event_40_unit in '..\..\Dionix\source\crm_add_event_40_unit.pas' {CRMADDEvent_40_Form},
  GetUser_unit in '..\..\Dionix\source\GetUser_unit.pas' {GetUser},
  contracts_u in '..\..\Dionix\source\contracts_u.pas' {ContractsForm},
  Tablets_u in '..\..\Dionix\source\Tablets_u.pas' {TabletsForm},
  VisuCB in '..\..\Dionix\source\VisuCB.pas' {EssaisCB},
  Codage_CB in '..\..\Dionix\source\Codage_CB.pas',
  scanner_act_u in '..\..\Dionix\source\scanner_act_u.pas' {Scanner_act},
  Scaner_TLB in '..\..\Dionix\source\Scaner_TLB.pas',
  Chect_Act_U in '..\..\Dionix\source\Chect_Act_U.pas' {Check_ActForm},
  scanner_pril_u in '..\..\Dionix\source\scanner_pril_u.pas' {Scanner_pril},
  Import_e_delivery in '..\..\Dionix\source\Import_e_delivery.pas' {Import_e_Delivery_Form},
  openwindow_u in '..\..\Dionix\source\openwindow_u.pas' {OpenWindowForm},
  doc_money_U in '..\..\Dionix\source\doc_money_U.pas' {Doc_MoneyForm},
  Regions_u in '..\..\Dionix\source\Regions_u.pas' {RegionsForm},
  Check_signedAct_U in '..\..\Dionix\source\Check_signedAct_U.pas' {Check_SignedActForm},
  Check_USERACTION_U in '..\..\Dionix\source\Check_USERACTION_U.pas' {Check_UserActionForm},
  opentime_u in '..\..\Dionix\source\opentime_u.pas' {OpenTimesForm},
  excel_Client_U in '..\..\Dionix\source\excel_Client_U.pas' {Excel_ClientForm},
  excel_SERVER_U in '..\..\Dionix\source\excel_SERVER_U.pas' {Excel_ServerForm},
  GET_grid_Dialog_u in '..\..\Dionix\source\GET_grid_Dialog_u.pas' {Get_GridDialog_Form},
  Get_GridHolding_Dialog_u in '..\..\Dionix\source\Get_GridHolding_Dialog_u.pas' {Get_GridHolding_DialogForm},
  ceferr in '..\..\Dionix\source\DCEF\src\ceferr.pas',
  cefgui in '..\..\Dionix\source\DCEF\src\cefgui.pas',
  ceflib in '..\..\Dionix\source\DCEF\src\ceflib.pas',
  cefvcl in '..\..\Dionix\source\DCEF\src\cefvcl.pas',
  ceffilescheme in '..\..\Dionix\source\DCEF\demos\filescheme\ceffilescheme.pas',
  Authentication in '..\..\Dionix\source\DCEF\demos\guiclient\Authentication.pas' {PasswordDlg},
  GoogleMap_U in '..\..\Dionix\source\GoogleMap_U.pas' {GoogleMap_Form},
  La_Round_No_u in '..\..\Dionix\source\La_Round_No_u.pas' {LA_Round_NOForm},
  Get_Grid_acBill_Info in '..\..\Dionix\source\Get_Grid_acBill_Info.pas' {Get_GridAC_BILL_INFO_Form},
  Get_GridDialog_CRM_CURATOR in '..\..\Dionix\source\Get_GridDialog_CRM_CURATOR.pas' {Get_Grid_CRM_CURATOR_Form},
  GetDate2_AC_BILL_u in '..\..\Dionix\source\GetDate2_AC_BILL_u.pas' {GetDate2_ACBILL_Form},
  UDC_TLB in '..\..\..\..\Program Files (x86)\Borland\Delphi7\Imports\UDC_TLB.pas',
  DebugUnit in '..\..\Dionix_CRM\source\Colib\DebugUnit.pas',
  BlackList_U in '..\..\Dionix\source\BlackList_U.pas' {BlackList_Form},
  Get_ACCOUNTdESCr_LOG in '..\..\Dionix\source\Get_ACCOUNTdESCr_LOG.pas' {Get_Account_Descr_Log};

{$R *.res}
                        
begin
  Application.Initialize;
  Application.Title := '-Дионикс2000-';
  Application.CreateForm(TLoginForm, LoginForm);
  Application.CreateForm(TEssaisCB, EssaisCB);
  Application.CreateForm(TCheck_ActForm, Check_ActForm);
  Application.CreateForm(TOpenWindowForm, OpenWindowForm);
  Application.CreateForm(TCheck_SignedActForm, Check_SignedActForm);
  Application.CreateForm(TCheck_UserActionForm, Check_UserActionForm);
  Application.CreateForm(TExcel_ClientForm, Excel_ClientForm);
  Application.CreateForm(TExcel_ServerForm, Excel_ServerForm);
  Application.CreateForm(TGet_GridHolding_DialogForm, Get_GridHolding_DialogForm);
  Application.CreateForm(TPasswordDlg, PasswordDlg);
  Application.CreateForm(TGet_GridAC_BILL_INFO_Form, Get_GridAC_BILL_INFO_Form);
  Application.CreateForm(TGet_Grid_CRM_CURATOR_Form, Get_Grid_CRM_CURATOR_Form);
  Application.Run;


end.

